// Formats the IR from collect.js as C#. No TypeSpec APIs in here — only strings.

import { str, xmlText } from "./names.js";

const HEADER = (namespace, usings) =>
  [
    "// <auto-generated>",
    "//   Generated by typespec-arm-csharp from the TypeSpec contract (src/spec). Do not edit:",
    "//   change the spec (or the emitter) and rebuild.",
    "// </auto-generated>",
    "#nullable enable",
    ...usings.map((u) => `using ${u};`),
    "",
    `namespace ${namespace};`,
    "",
  ].join("\n");

const summary = (doc, indent = "") => (doc ? `${indent}/// <summary>${xmlText(doc)}</summary>\n` : "");

const MAP_METHODS = { get: "MapGet", post: "MapPost", put: "MapPut", delete: "MapDelete", patch: "MapPatch" };
const FROM = { path: "FromRoute", query: "FromQuery", header: "FromHeader" };

/** Records, enums, discriminated unions and request validators. */
export function renderModels(ir, namespace) {
  const out = [HEADER(namespace, ["System", "System.Collections.Generic", "System.Text.Json.Serialization", "Olve.Results", "Olve.Validation"])];

  for (const e of ir.enums.values()) {
    let s = summary(e.doc);
    if (!e.numeric) s += `[JsonConverter(typeof(JsonStringEnumConverter<${e.name}>))]\n`;
    s += `public enum ${e.name}\n{\n`;
    for (const m of e.members) {
      s += summary(m.doc, "    ");
      s += e.numeric ? `    ${m.name} = ${m.value},\n` : `    [JsonStringEnumMemberName(${str(m.value)})]\n    ${m.name},\n`;
    }
    out.push(`${s}}\n`);
  }

  for (const u of ir.unions.values()) {
    let s = summary(u.doc);
    s += `[JsonPolymorphic(TypeDiscriminatorPropertyName = ${str(u.discriminator)})]\n`;
    for (const v of u.variants) s += `[JsonDerivedType(typeof(${v.name}), ${str(v.key)})]\n`;
    if (!u.events) {
      s += `public abstract record ${u.name};\n`;
    } else {
      // An SSE event union: each event knows its event name (its `type`, written by the polymorphism).
      s += `public abstract record ${u.name} : IArmEvent\n{\n`;
      s += "    /// <summary>Every event name (<c>type</c>) of the stream, in contract order.</summary>\n";
      s += `    public static IReadOnlyList<string> EventTypes { get; } = [${u.variants.map((v) => str(v.key)).join(", ")}];\n\n`;
      s += "    /// <inheritdoc />\n    [JsonIgnore]\n    public abstract string EventType { get; }\n}\n";
    }
    out.push(s);
  }

  for (const m of ir.models.values()) {
    let s = m.writableOf
      ? `/// <summary>Request shape of <see cref="${m.writableOf}"/> (only the properties a client may send).</summary>\n`
      : summary(m.doc);
    s += `public sealed record ${m.name}${m.union ? ` : ${m.union.name}` : ""}\n{\n`;
    const members = m.props.map((p) => renderProperty(p));
    if (m.union?.events) members.unshift(`    /// <inheritdoc />\n    [JsonIgnore]\n    public override string EventType => ${str(m.union.key)};\n`);
    s += members.join("\n");
    out.push(`${s}}\n`);
  }

  for (const v of ir.validators) {
    let s = `/// <summary>Validates <see cref="${v.model}"/> against the spec's constraints.</summary>\n`;
    s += `public sealed class ${v.name} : IValidator<${v.model}>\n{\n`;
    s += `    public Result Validate(${v.model} value) => Result.Concat(\n    [\n`;
    for (const r of v.rules) s += `        ${r.test} ? new ResultProblem(${str(r.message)}) : Result.Success(),\n`;
    s += "    ]);\n}\n";
    out.push(s);
  }

  return out.join("\n");
}

function renderProperty(p) {
  const attrs = [`JsonPropertyName(${str(p.wire)})`];
  // Optional, non-nullable: omit rather than write `null`. Nullable properties always write.
  if (p.optional && !p.nullable) attrs.push("JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)");
  return (
    summary(p.doc, "    ") +
    `    [${attrs.join(", ")}]\n` +
    `    public ${p.optional ? "" : "required "}${p.type} ${p.name} { get; init; }\n`
  );
}

/** Per-operation request records + handler interfaces, the operation table and MapArmApi. */
export function renderApi(ir, namespace) {
  const out = [
    HEADER(namespace, [
      "System",
      "System.Collections.Generic",
      "System.Threading",
      "Microsoft.AspNetCore.Builder",
      "Microsoft.AspNetCore.Http",
      "Microsoft.AspNetCore.Mvc",
      "Microsoft.AspNetCore.Routing",
      "Olve.MinimalApi",
      "Olve.Results",
    ]),
  ];

  for (const o of ir.operations) {
    const fields = [...o.params.map((p) => `${p.type} ${p.name}`), ...(o.body ? [`${o.body.type} Body`] : [])];
    let s = `/// <summary>Input of <c>${o.operationId}</c> (${o.verb.toUpperCase()} ${o.path}).</summary>\n`;
    s += `public sealed record ${o.name}Request${fields.length ? `(${fields.join(", ")})` : ""};\n\n`;
    s += summary(o.doc);
    s += `public interface I${o.name}Handler : IHandler<${o.name}Request${o.success.type ? `, ${responseType(o.success)}` : ""}>;\n`;
    out.push(s);
  }

  let table = "/// <summary>Every operation's id, success status and declared error statuses.</summary>\n";
  table += "public static class ArmOperations\n{\n";
  for (const o of ir.operations) {
    table += `    public static readonly ArmOperation ${o.name} = new(${str(o.operationId)}, ${o.success.status}, [${o.errors.map((e) => e.status).join(", ")}]);\n`;
  }
  out.push(`${table}}\n`);

  let endpoints = "/// <summary>The route builder of each mapped operation, for app-side conventions (auth, rate limits, …).</summary>\n";
  endpoints += "public sealed class ArmEndpoints\n{\n";
  endpoints += ir.operations.map((o) => `    public required RouteHandlerBuilder ${o.name} { get; init; }\n`).join("");
  out.push(`${endpoints}}\n`);

  let api = "public static class ArmApi\n{\n";
  api += "    /// <summary>Every operation's handler interface; each must have a registered implementation.</summary>\n";
  api += `    public static IReadOnlyList<Type> HandlerTypes { get; } =\n    [\n${ir.operations.map((o) => `        typeof(I${o.name}Handler),\n`).join("")}    ];\n\n`;
  api += "    /// <summary>Maps every contract operation onto its handler interface.</summary>\n";
  api += "    public static ArmEndpoints MapArmApi(this IEndpointRouteBuilder app) => new()\n    {\n";
  api += ir.operations.map((o) => renderEndpoint(o, ir)).join("");
  api += "    };\n}\n";
  out.push(api);

  const parsed = [...new Set(ir.operations.flatMap((o) => o.params.map((p) => stringEnumOf(p, ir)).filter(Boolean)))];
  if (parsed.length) out.push(renderEnumParsers(parsed.map((name) => ir.enums.get(name))));

  return out.join("\n");
}

/** What a handler returns on success: the body, or for an SSE stream the events with their ids. */
function responseType(success) {
  return success.stream ? `IAsyncEnumerable<ArmSseItem<${success.type}>>` : success.type;
}

/** The string enum a parameter binds to, if any (minimal APIs would parse it by C# member name). */
function stringEnumOf(p, ir) {
  const e = ir.enums.get(p.type.replace(/\?$/, ""));
  return e && !e.numeric ? e.name : undefined;
}

/** Parses string-enum parameters by their wire values; anything else is a binding failure. */
function renderEnumParsers(enums) {
  let s = "/// <summary>Parses string-enum parameters by their wire values (minimal APIs only know member names).</summary>\n";
  s += "internal static class ArmParameters\n{\n";
  s += enums
    .map((e) => {
      let m = `    public static ${e.name} Parse${e.name}(string value, string parameter) => value switch\n    {\n`;
      for (const member of e.members) m += `        ${str(member.value)} => ${e.name}.${member.name},\n`;
      m += '        _ => throw new BadHttpRequestException($"Failed to bind parameter \\"{parameter}\\" from \\"{value}\\"."),\n';
      return `${m}    };\n`;
    })
    .join("\n");
  return `${s}}\n`;
}

function renderEndpoint(o, ir) {
  const route = MAP_METHODS[o.verb]
    ? `app.${MAP_METHODS[o.verb]}(${str(o.path)}, `
    : `app.MapMethods(${str(o.path)}, [${str(o.verb.toUpperCase())}], `;
  const lambdaParams = [
    `[FromServices] I${o.name}Handler handler`,
    ...o.params.map((p) => {
      // String enums bind as strings and are parsed by wire value (see renderEnumParsers);
      // explode:false lists bind as one string and are split (ArmQuery.List).
      const type = stringEnumOf(p, ir) || p.list ? (p.type.endsWith("?") ? "string?" : "string") : p.type;
      return `[${FROM[p.kind]}(Name = ${str(p.wire)})] ${type} ${p.local}`;
    }),
    ...(o.body ? [`[FromBody] ${o.body.type} body`] : []),
    "CancellationToken ct",
  ];
  const arg = (p) => {
    if (p.list) return `ArmQuery.List(${p.local})`;
    const e = stringEnumOf(p, ir);
    if (!e) return p.local;
    const parse = `ArmParameters.Parse${e}(${p.local}, ${str(p.wire)})`;
    return p.type.endsWith("?") ? `${p.local} is null ? null : ${parse}` : parse;
  };
  const args = [...o.params.map(arg), ...(o.body ? ["body"] : [])].join(", ");
  const call = o.success.type ? "HandleAsync" : "RunAsync";
  const map = o.success.stream ? "ArmResults.Stream" : "ArmResults.Map";
  const i = "        ";
  let s = `${i}${o.name} = ${route}async (\n`;
  s += lambdaParams.map((p) => `${i}        ${p}`).join(",\n");
  s += ") =>\n";
  s += `${i}        ${map}(await handler.${call}(new ${o.name}Request(${args}), ct), ArmOperations.${o.name}))\n`;
  s += `${i}    .WithName(${str(o.operationId)})\n`;
  s += `${i}    .WithMetadata(ArmOperations.${o.name})`;
  if (o.body?.validator) s += `\n${i}    .WithValidation<${o.body.type}, ${o.body.validator}>()`;
  s += o.success.stream
    ? `\n${i}    .Produces<${o.success.type}>(${o.success.status}, "text/event-stream")`
    : `\n${i}    .Produces${o.success.type ? `<${o.success.type}>` : ""}(${o.success.status})`;
  for (const e of o.errors) s += `\n${i}    .Produces${e.type ? `<${e.type}>` : ""}(${e.status})`;
  return `${s},\n`;
}

/** The System.Text.Json source-generation context for every DTO. */
export function renderJsonContext(ir, namespace) {
  let s = HEADER(namespace, ["System.Collections.Generic", "System.Text.Json", "System.Text.Json.Serialization", "Olve.Results"]);
  s += "\n[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, AllowOutOfOrderMetadataProperties = true)]\n";
  for (const t of ir.jsonTypes) s += `[JsonSerializable(typeof(${t}))]\n`;
  s += "public partial class ArmJsonContext : JsonSerializerContext;\n";
  return s;
}
