// <auto-generated>
//   Generated by typespec-arm-csharp from the TypeSpec contract (src/spec). Do not edit:
//   change the spec (or the emitter) and rebuild.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Olve.MinimalApi;
using Olve.Results;

namespace Fixture.Api;

/// <summary>Input of <c>Shapes_get</c> (GET /api/shapes/{id}).</summary>
public sealed record ShapesGetRequest(string Id);

public interface IShapesGetHandler : IHandler<ShapesGetRequest, Shape>;

/// <summary>Input of <c>Tags_echo</c> (GET /api/tags).</summary>
public sealed record TagsEchoRequest(IReadOnlyList<string> Names);

/// <summary>Echoes a required `explode: false` list (`?names=a,b`).</summary>
public interface ITagsEchoHandler : IHandler<TagsEchoRequest, IReadOnlyList<string>>;

/// <summary>Input of <c>WidgetEvents_stream</c> (GET /api/widget-events).</summary>
public sealed record WidgetEventsStreamRequest(IReadOnlyList<string>? Type, string? LastEventId);

/// <summary>Streams widget events; `type` limits them to these event names.</summary>
public interface IWidgetEventsStreamHandler : IHandler<WidgetEventsStreamRequest, IAsyncEnumerable<ArmSseItem<WidgetEvent>>>;

/// <summary>Input of <c>Widgets_create</c> (POST /api/widgets).</summary>
public sealed record WidgetsCreateRequest(WidgetCreate Body);

public interface IWidgetsCreateHandler : IHandler<WidgetsCreateRequest, Widget>;

/// <summary>Input of <c>Widgets_delete</c> (DELETE /api/widgets/{id}).</summary>
public sealed record WidgetsDeleteRequest(string Id);

public interface IWidgetsDeleteHandler : IHandler<WidgetsDeleteRequest>;

/// <summary>Input of <c>Widgets_list</c> (GET /api/widgets).</summary>
public sealed record WidgetsListRequest(Color? Color, int? Limit, string? RequestId);

/// <summary>List widgets.</summary>
public interface IWidgetsListHandler : IHandler<WidgetsListRequest, IReadOnlyList<Widget>>;

/// <summary>Input of <c>Widgets_update</c> (PUT /api/widgets/{id}).</summary>
public sealed record WidgetsUpdateRequest(string Id, bool? DryRun, WidgetWritable Body);

public interface IWidgetsUpdateHandler : IHandler<WidgetsUpdateRequest, Widget>;

/// <summary>Every operation's id, success status and declared error statuses.</summary>
public static class ArmOperations
{
    public static readonly ArmOperation ShapesGet = new("Shapes_get", 200, [404]);
    public static readonly ArmOperation TagsEcho = new("Tags_echo", 200, []);
    public static readonly ArmOperation WidgetEventsStream = new("WidgetEvents_stream", 200, [400]);
    public static readonly ArmOperation WidgetsCreate = new("Widgets_create", 200, [400]);
    public static readonly ArmOperation WidgetsDelete = new("Widgets_delete", 204, [404]);
    public static readonly ArmOperation WidgetsList = new("Widgets_list", 200, []);
    public static readonly ArmOperation WidgetsUpdate = new("Widgets_update", 200, [400, 404]);
}

/// <summary>The route builder of each mapped operation, for app-side conventions (auth, rate limits, …).</summary>
public sealed class ArmEndpoints
{
    public required RouteHandlerBuilder ShapesGet { get; init; }
    public required RouteHandlerBuilder TagsEcho { get; init; }
    public required RouteHandlerBuilder WidgetEventsStream { get; init; }
    public required RouteHandlerBuilder WidgetsCreate { get; init; }
    public required RouteHandlerBuilder WidgetsDelete { get; init; }
    public required RouteHandlerBuilder WidgetsList { get; init; }
    public required RouteHandlerBuilder WidgetsUpdate { get; init; }
}

public static class ArmApi
{
    /// <summary>Every operation's handler interface; each must have a registered implementation.</summary>
    public static IReadOnlyList<Type> HandlerTypes { get; } =
    [
        typeof(IShapesGetHandler),
        typeof(ITagsEchoHandler),
        typeof(IWidgetEventsStreamHandler),
        typeof(IWidgetsCreateHandler),
        typeof(IWidgetsDeleteHandler),
        typeof(IWidgetsListHandler),
        typeof(IWidgetsUpdateHandler),
    ];

    /// <summary>Maps every contract operation onto its handler interface.</summary>
    public static ArmEndpoints MapArmApi(this IEndpointRouteBuilder app) => new()
    {
        ShapesGet = app.MapGet("/api/shapes/{id}", async (
                [FromServices] IShapesGetHandler handler,
                [FromRoute(Name = "id")] string id,
                CancellationToken ct) =>
                ArmResults.Map(await handler.HandleAsync(new ShapesGetRequest(id), ct), ArmOperations.ShapesGet))
            .WithName("Shapes_get")
            .WithMetadata(ArmOperations.ShapesGet)
            .Produces<Shape>(200)
            .Produces<IReadOnlyList<ResultProblem>>(404),
        TagsEcho = app.MapGet("/api/tags", async (
                [FromServices] ITagsEchoHandler handler,
                [FromQuery(Name = "names")] string names,
                CancellationToken ct) =>
                ArmResults.Map(await handler.HandleAsync(new TagsEchoRequest(ArmQuery.List(names)), ct), ArmOperations.TagsEcho))
            .WithName("Tags_echo")
            .WithMetadata(ArmOperations.TagsEcho)
            .Produces<IReadOnlyList<string>>(200),
        WidgetEventsStream = app.MapGet("/api/widget-events", async (
                [FromServices] IWidgetEventsStreamHandler handler,
                [FromQuery(Name = "type")] string? type,
                [FromHeader(Name = "Last-Event-ID")] string? lastEventId,
                CancellationToken ct) =>
                ArmResults.Stream(await handler.HandleAsync(new WidgetEventsStreamRequest(ArmQuery.List(type), lastEventId), ct), ArmOperations.WidgetEventsStream))
            .WithName("WidgetEvents_stream")
            .WithMetadata(ArmOperations.WidgetEventsStream)
            .Produces<WidgetEvent>(200, "text/event-stream")
            .Produces<IReadOnlyList<ResultProblem>>(400),
        WidgetsCreate = app.MapPost("/api/widgets", async (
                [FromServices] IWidgetsCreateHandler handler,
                [FromBody] WidgetCreate body,
                CancellationToken ct) =>
                ArmResults.Map(await handler.HandleAsync(new WidgetsCreateRequest(body), ct), ArmOperations.WidgetsCreate))
            .WithName("Widgets_create")
            .WithMetadata(ArmOperations.WidgetsCreate)
            .WithValidation<WidgetCreate, WidgetCreateValidator>()
            .Produces<Widget>(200)
            .Produces<IReadOnlyList<ResultProblem>>(400),
        WidgetsDelete = app.MapDelete("/api/widgets/{id}", async (
                [FromServices] IWidgetsDeleteHandler handler,
                [FromRoute(Name = "id")] string id,
                CancellationToken ct) =>
                ArmResults.Map(await handler.RunAsync(new WidgetsDeleteRequest(id), ct), ArmOperations.WidgetsDelete))
            .WithName("Widgets_delete")
            .WithMetadata(ArmOperations.WidgetsDelete)
            .Produces(204)
            .Produces<IReadOnlyList<ResultProblem>>(404),
        WidgetsList = app.MapGet("/api/widgets", async (
                [FromServices] IWidgetsListHandler handler,
                [FromQuery(Name = "color")] string? color,
                [FromQuery(Name = "limit")] int? limit,
                [FromHeader(Name = "x-request-id")] string? requestId,
                CancellationToken ct) =>
                ArmResults.Map(await handler.HandleAsync(new WidgetsListRequest(color is null ? null : ArmParameters.ParseColor(color, "color"), limit, requestId), ct), ArmOperations.WidgetsList))
            .WithName("Widgets_list")
            .WithMetadata(ArmOperations.WidgetsList)
            .Produces<IReadOnlyList<Widget>>(200),
        WidgetsUpdate = app.MapPut("/api/widgets/{id}", async (
                [FromServices] IWidgetsUpdateHandler handler,
                [FromRoute(Name = "id")] string id,
                [FromQuery(Name = "dryRun")] bool? dryRun,
                [FromBody] WidgetWritable body,
                CancellationToken ct) =>
                ArmResults.Map(await handler.HandleAsync(new WidgetsUpdateRequest(id, dryRun, body), ct), ArmOperations.WidgetsUpdate))
            .WithName("Widgets_update")
            .WithMetadata(ArmOperations.WidgetsUpdate)
            .WithValidation<WidgetWritable, WidgetWritableValidator>()
            .Produces<Widget>(200)
            .Produces<IReadOnlyList<ResultProblem>>(400)
            .Produces<IReadOnlyList<ResultProblem>>(404),
    };
}

/// <summary>Parses string-enum parameters by their wire values (minimal APIs only know member names).</summary>
internal static class ArmParameters
{
    public static Color ParseColor(string value, string parameter) => value switch
    {
        "red" => Color.Red,
        "green" => Color.Green,
        _ => throw new BadHttpRequestException($"Failed to bind parameter \"{parameter}\" from \"{value}\"."),
    };
}
