// <auto-generated>
//   Generated by typespec-arm-csharp from the TypeSpec contract (src/spec). Do not edit:
//   change the spec (or the emitter) and rebuild.
// </auto-generated>
#nullable enable
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Olve.Results;

namespace Fixture.Api;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, AllowOutOfOrderMetadataProperties = true)]
[JsonSerializable(typeof(ArmErrorEnvelope))]
[JsonSerializable(typeof(Color))]
[JsonSerializable(typeof(IReadOnlyList<Widget>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(Priority))]
[JsonSerializable(typeof(Shape))]
[JsonSerializable(typeof(Widget))]
[JsonSerializable(typeof(WidgetCreate))]
[JsonSerializable(typeof(WidgetEvent))]
[JsonSerializable(typeof(WidgetWritable))]
public partial class ArmJsonContext : JsonSerializerContext;
