// <auto-generated>
//   Generated by typespec-arm-csharp from the TypeSpec contract (src/spec). Do not edit:
//   change the spec (or the emitter) and rebuild.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Olve.Results;
using Olve.Validation;

namespace Fixture.Api;

[JsonConverter(typeof(JsonStringEnumConverter<Color>))]
public enum Color
{
    [JsonStringEnumMemberName("red")]
    Red,
    /// <summary>The default.</summary>
    [JsonStringEnumMemberName("green")]
    Green,
}

public enum Priority
{
    Low = 1,
    High = 2,
}

/// <summary>A shape, discriminated on `kind`.</summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(Circle), "circle")]
[JsonDerivedType(typeof(Square), "square")]
public abstract record Shape;

public sealed record Circle : Shape
{
    [JsonPropertyName("radius")]
    public required double Radius { get; init; }
}

public sealed record Square : Shape
{
    [JsonPropertyName("side")]
    public required double Side { get; init; }
}

/// <summary>A widget.</summary>
public sealed record Widget
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>Set once, at creation.</summary>
    [JsonPropertyName("serial")]
    public required string Serial { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("color"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Color? Color { get; init; }

    [JsonPropertyName("priority")]
    public required Priority Priority { get; init; }

    [JsonPropertyName("description")]
    public required string? Description { get; init; }

    [JsonPropertyName("parent")]
    public string? Parent { get; init; }

    [JsonPropertyName("tags"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Tags { get; init; }

    [JsonPropertyName("labels"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, string>? Labels { get; init; }

    [JsonPropertyName("weight"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Weight { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("shape")]
    public required Shape Shape { get; init; }
}

/// <summary>Request shape of <see cref="Widget"/> (only the properties a client may send).</summary>
public sealed record WidgetCreate
{
    /// <summary>Set once, at creation.</summary>
    [JsonPropertyName("serial")]
    public required string Serial { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("color"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Color? Color { get; init; }

    [JsonPropertyName("priority")]
    public required Priority Priority { get; init; }

    [JsonPropertyName("description")]
    public required string? Description { get; init; }

    [JsonPropertyName("parent")]
    public string? Parent { get; init; }

    [JsonPropertyName("tags"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Tags { get; init; }

    [JsonPropertyName("labels"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, string>? Labels { get; init; }

    [JsonPropertyName("weight"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Weight { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("shape")]
    public required Shape Shape { get; init; }
}

/// <summary>Request shape of <see cref="Widget"/> (only the properties a client may send).</summary>
public sealed record WidgetWritable
{
    /// <summary>Set once, at creation.</summary>
    [JsonPropertyName("serial")]
    public required string Serial { get; init; }

    /// <summary>Only sent when updating.</summary>
    [JsonPropertyName("note"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Note { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("color"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Color? Color { get; init; }

    [JsonPropertyName("priority")]
    public required Priority Priority { get; init; }

    [JsonPropertyName("description")]
    public required string? Description { get; init; }

    [JsonPropertyName("parent")]
    public string? Parent { get; init; }

    [JsonPropertyName("tags"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Tags { get; init; }

    [JsonPropertyName("labels"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, string>? Labels { get; init; }

    [JsonPropertyName("weight"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Weight { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("shape")]
    public required Shape Shape { get; init; }
}

/// <summary>Validates <see cref="WidgetCreate"/> against the spec's constraints.</summary>
public sealed class WidgetCreateValidator : IValidator<WidgetCreate>
{
    public Result Validate(WidgetCreate value) => Result.Concat(
    [
        value.Serial is null ? new ResultProblem("'serial' is required.") : Result.Success(),
        value.Name is null ? new ResultProblem("'name' is required.") : Result.Success(),
        value.Name is { Length: < 1 } ? new ResultProblem("'name' must be at least 1 character.") : Result.Success(),
        value.Name is { Length: > 50 } ? new ResultProblem("'name' cannot exceed 50 characters.") : Result.Success(),
        value.Tags is { Count: > 10 } ? new ResultProblem("'tags' cannot have more than 10 items.") : Result.Success(),
        value.Weight < 0 ? new ResultProblem("'weight' must be at least 0.") : Result.Success(),
        value.Weight > 100 ? new ResultProblem("'weight' cannot exceed 100.") : Result.Success(),
        value.Shape is null ? new ResultProblem("'shape' is required.") : Result.Success(),
    ]);
}

/// <summary>Validates <see cref="WidgetWritable"/> against the spec's constraints.</summary>
public sealed class WidgetWritableValidator : IValidator<WidgetWritable>
{
    public Result Validate(WidgetWritable value) => Result.Concat(
    [
        value.Serial is null ? new ResultProblem("'serial' is required.") : Result.Success(),
        value.Name is null ? new ResultProblem("'name' is required.") : Result.Success(),
        value.Name is { Length: < 1 } ? new ResultProblem("'name' must be at least 1 character.") : Result.Success(),
        value.Name is { Length: > 50 } ? new ResultProblem("'name' cannot exceed 50 characters.") : Result.Success(),
        value.Tags is { Count: > 10 } ? new ResultProblem("'tags' cannot have more than 10 items.") : Result.Success(),
        value.Weight < 0 ? new ResultProblem("'weight' must be at least 0.") : Result.Success(),
        value.Weight > 100 ? new ResultProblem("'weight' cannot exceed 100.") : Result.Success(),
        value.Shape is null ? new ResultProblem("'shape' is required.") : Result.Success(),
    ]);
}
